/**
 * devlog — self-contained HTML dashboard renderer.
 *
 * Produces docs/dev-state/dashboard.html: a single vanilla HTML/CSS/JS file,
 * no build step, no external requests — opens directly via file:// with no
 * server. Regenerated by writeSnapshot() alongside decisions.md/roadmap.md/
 * state.json, so it's always in sync with the last mutating command.
 *
 * Roadmap/decision text fields are free-text supplied via CLI flags,
 * potentially by an LLM agent, and are therefore untrusted. The client
 * script only ever places that text into the DOM via textContent /
 * createTextNode / dataset — never innerHTML — so it can't execute as
 * markup when the file is opened in a browser.
 */
import { nowIso, ROADMAP_STATUSES } from './db.ts';
import type { DecisionRow } from './decisions.ts';
import type { RoadmapRow, RoadmapHistoryRow } from './roadmap.ts';

export type RoadmapWithHistory = RoadmapRow & { history: RoadmapHistoryRow[] };

/**
 * Escape the one character that could prematurely close the embedded
 * <script type="application/json"> block. <script> is an HTML "raw text"
 * element, so the parser does not decode entities inside it — writing an
 * HTML entity here would corrupt JSON.parse. Replacing literal `<` with the
 * JSON-legal < escape keeps the payload valid JSON (JSON.parse
 * restores the real `<`) while guaranteeing `</script>` / `<!--` can never
 * appear literally in the emitted markup.
 */
function embedJson(value: unknown): string {
  return JSON.stringify(value).replace(/</g, '\\u003c');
}

function escapeText(s: string): string {
  return s.replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' })[c]!);
}

const STATUS_LABEL: Record<string, string> = {
  planned: 'Planned',
  in_progress: 'In Progress',
  blocked: 'Blocked',
  done: 'Done',
  abandoned: 'Abandoned',
};

const CSS = `
:root {
  color-scheme: dark;
  --bg: #0f1115; --panel: #171a21; --panel-2: #1e222b; --border: #2a2f3a;
  --text: #e6e8ec; --muted: #9aa1ad; --accent: #7c9cff;
  --planned: #5b8def; --in_progress: #e0a63a; --blocked: #e0555a;
  --done: #4caf7d; --abandoned: #6b7280;
}
* { box-sizing: border-box; }
body { margin: 0; font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: var(--bg); color: var(--text); }
main, header { max-width: 1400px; margin: 0 auto; padding: 24px; }
header { padding-bottom: 0; }
h1 { margin: 0 0 4px; font-size: 22px; }
h2 { font-size: 16px; margin: 0 0 12px; }
.meta { color: var(--muted); font-size: 12px; }
.stats { display: flex; gap: 10px; margin: 16px 0; flex-wrap: wrap; }
.stat { background: var(--panel); border: 1px solid var(--border); border-radius: 8px; padding: 8px 12px; border-left: 3px solid var(--stat-color, var(--accent)); font-size: 13px; }
.stat b { font-size: 16px; margin-right: 4px; }
#search { width: 100%; max-width: 320px; padding: 8px 10px; margin-bottom: 20px; border-radius: 6px; border: 1px solid var(--border); background: var(--panel); color: var(--text); }
.board { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin-bottom: 32px; align-items: start; }
.column h3 { font-size: 12px; text-transform: uppercase; letter-spacing: .04em; color: var(--muted); margin: 0 0 10px; }
.column-list { display: flex; flex-direction: column; gap: 8px; }
.card { background: var(--panel); border: 1px solid var(--border); border-left: 3px solid var(--card-color, var(--accent)); border-radius: 8px; padding: 2px 12px; }
.card summary { list-style: none; cursor: pointer; padding: 8px 0; display: flex; gap: 8px; align-items: baseline; }
.card summary::-webkit-details-marker { display: none; }
.card-id { color: var(--muted); font-size: 11px; flex-shrink: 0; }
.card-title { font-weight: 500; }
.card-tags { display: flex; gap: 6px; flex-wrap: wrap; padding-bottom: 8px; }
.tag { background: var(--panel-2); border-radius: 4px; padding: 2px 6px; font-size: 11px; color: var(--muted); }
.tag-plan { color: var(--accent); }
.card-body { padding: 4px 0 10px; border-top: 1px solid var(--border); font-size: 12.5px; }
.card-body p { margin: 6px 0; }
.card-body strong { color: var(--muted); font-weight: 600; }
.variance { color: var(--in_progress); }
.blocked { color: var(--blocked); }
.history { list-style: none; margin: 8px 0 0; padding: 0; color: var(--muted); font-size: 11.5px; }
.history li { padding: 2px 0; }
.decision-list { display: flex; flex-direction: column; gap: 10px; }
.decision { background: var(--panel); border: 1px solid var(--border); border-radius: 8px; padding: 12px 14px; }
.decision-head { display: flex; align-items: center; gap: 8px; margin-bottom: 4px; flex-wrap: wrap; }
.decision-head .card-title { font-weight: 600; }
.decision p { margin: 4px 0; }
.decision a { color: var(--accent); }
.empty { color: var(--muted); padding: 6px 0; }
.hidden { display: none !important; }
@media (max-width: 480px) {
  main, header { padding: 16px; }
}
`;

const CLIENT_JS = `
(function () {
  var data = JSON.parse(document.getElementById('devlog-data').textContent);
  var STATUSES = ${JSON.stringify(ROADMAP_STATUSES)};

  function el(tag, className) {
    var e = document.createElement(tag);
    if (className) e.className = className;
    return e;
  }

  function field(container, label, value, cls) {
    if (!value) return;
    var p = el('p', cls);
    var strong = el('strong');
    strong.textContent = label + ': ';
    p.appendChild(strong);
    p.appendChild(document.createTextNode(value));
    container.appendChild(p);
  }

  function roadmapCard(r) {
    var card = el('details', 'card');
    card.style.setProperty('--card-color', 'var(--' + r.status + ')');
    card.dataset.title = r.title.toLowerCase();

    var summary = el('summary');
    var idSpan = el('span', 'card-id');
    idSpan.textContent = '#' + r.id;
    var titleSpan = el('span', 'card-title');
    titleSpan.textContent = r.title;
    summary.appendChild(idSpan);
    summary.appendChild(titleSpan);
    card.appendChild(summary);

    var tags = el('div', 'card-tags');
    var catTag = el('span', 'tag');
    catTag.textContent = r.category;
    tags.appendChild(catTag);
    if (r.plan_ref) {
      var planTag = el('span', 'tag tag-plan');
      planTag.textContent = r.plan_ref;
      tags.appendChild(planTag);
    }
    card.appendChild(tags);

    var body = el('div', 'card-body');
    field(body, 'Description', r.description);
    field(body, 'Planned', r.planned_scope);
    field(body, 'Actual', r.actual_scope);
    field(body, 'Variance', r.variance_notes, 'variance');
    field(body, 'Blocked', r.blocked_reason, 'blocked');
    if (r.history && r.history.length) {
      var hist = el('ul', 'history');
      r.history.forEach(function (h) {
        var li = el('li');
        li.textContent = h.changed_at + '  ' + (h.from_status || '∅') + ' → ' + h.to_status + (h.note ? ' (' + h.note + ')' : '');
        hist.appendChild(li);
      });
      body.appendChild(hist);
    }
    card.appendChild(body);
    return card;
  }

  function renderBoard() {
    var board = document.getElementById('board');
    STATUSES.forEach(function (status) {
      var items = data.roadmap.filter(function (r) { return r.status === status; });
      var col = el('div', 'column');
      var h3 = el('h3');
      h3.textContent = ${JSON.stringify(STATUS_LABEL)}[status] + ' (' + items.length + ')';
      col.appendChild(h3);
      var list = el('div', 'column-list');
      if (items.length === 0) {
        var empty = el('div', 'empty');
        empty.textContent = 'No items';
        list.appendChild(empty);
      } else {
        items.forEach(function (r) { list.appendChild(roadmapCard(r)); });
      }
      col.appendChild(list);
      board.appendChild(col);
    });
  }

  function decisionCard(d) {
    var card = el('div', 'decision');
    card.id = 'decision-' + d.id;
    card.dataset.title = d.title.toLowerCase();

    var head = el('div', 'decision-head');
    var idSpan = el('span', 'card-id');
    idSpan.textContent = '#' + d.id;
    var titleSpan = el('span', 'card-title');
    titleSpan.textContent = d.title;
    var statusTag = el('span', 'tag');
    statusTag.textContent = d.status;
    head.appendChild(idSpan);
    head.appendChild(titleSpan);
    head.appendChild(statusTag);
    card.appendChild(head);

    var meta = el('div', 'meta');
    meta.textContent = d.created_at + (d.author ? ' · ' + d.author : '') + (d.plan_ref ? ' · ' + d.plan_ref : '');
    card.appendChild(meta);

    field(card, 'Context', d.context);
    field(card, 'Decision', d.decision);
    field(card, 'Rationale', d.rationale);
    field(card, 'Consequences', d.consequences);
    if (d.supersedes) {
      var sup = el('p');
      sup.appendChild(document.createTextNode('Supersedes '));
      var link = document.createElement('a');
      link.href = '#decision-' + d.supersedes;
      link.textContent = '#' + d.supersedes;
      sup.appendChild(link);
      card.appendChild(sup);
    }
    return card;
  }

  function renderDecisions() {
    var list = document.getElementById('decisions-list');
    if (data.decisions.length === 0) {
      var empty = el('div', 'empty');
      empty.textContent = 'No decisions logged yet.';
      list.appendChild(empty);
      return;
    }
    data.decisions.forEach(function (d) { list.appendChild(decisionCard(d)); });
  }

  function setupFilter() {
    document.getElementById('search').addEventListener('input', function (e) {
      var q = e.target.value.trim().toLowerCase();
      document.querySelectorAll('[data-title]').forEach(function (node) {
        node.classList.toggle('hidden', q.length > 0 && node.dataset.title.indexOf(q) === -1);
      });
    });
  }

  renderBoard();
  renderDecisions();
  setupFilter();
})();
`;

export function renderDashboard(decisions: DecisionRow[], roadmap: RoadmapWithHistory[]): string {
  const generatedAt = nowIso();
  const counts: Record<string, number> = {};
  for (const s of ROADMAP_STATUSES) counts[s] = 0;
  for (const r of roadmap) counts[r.status] = (counts[r.status] ?? 0) + 1;

  const statChips =
    ROADMAP_STATUSES.map(
      (s) =>
        `<div class="stat" style="--stat-color:var(--${s})"><b>${counts[s]}</b>${escapeText(STATUS_LABEL[s])}</div>`,
    ).join('') + `<div class="stat"><b>${decisions.length}</b>Decisions</div>`;

  const payload = embedJson({ generatedAt, decisions, roadmap });

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>devlog dashboard</title>
<style>${CSS}</style>
</head>
<body>
<header>
  <h1>devlog dashboard</h1>
  <div class="meta">Generated ${escapeText(generatedAt)}</div>
  <div class="stats">${statChips}</div>
</header>
<main>
  <input id="search" type="search" placeholder="Filter by title…">
  <section id="board" class="board"></section>
  <section class="decisions">
    <h2>Decisions</h2>
    <div id="decisions-list" class="decision-list"></div>
  </section>
</main>
<script type="application/json" id="devlog-data">${payload}</script>
<script>${CLIENT_JS}</script>
</body>
</html>
`;
}
